### ISSUE TITLE
서버 시간이 뭔가 이상하다

### ISSUE THREAD

**Issue by iml1111** [iml1111/SejongSQL#12]
ㅋㅋ;
![image](https://user-images.githubusercontent.com/29897277/161416153-55a9eda8-90df-4358-8334-a18067f5d09c.png)

**Comment by 837477** [comment]
![image](https://user-images.githubusercontent.com/37999795/162182513-6b7c846f-dc51-464d-a57a-99f0cb88054c.png)
변경했습니다 :)
