### ISSUE TITLE
사용자 권한 ERD 변경으로 인한 코드 수정

### ISSUE THREAD

**Issue by 837477** [iml1111/SejongSQL#20]
@akshxl09 태보의 의견
-> 현재 user_belong_class에 사용자의 권한이 존재해서 상당히 번거로운 상황들이 계속해서 발견됨.

현재는 API 호출할 때, 교수 및 조교만 호출할 수 있는 API가 존재 => 즉, 분반 관리자 전용 API
그런데 현재 ERD는 user table이 아닌, User_belong_class에서 사용자의 권환이 확인 가능함
왜냐하면, 한 아이디로 어떤 분반에서는 조교 / 어떤 분반에서는 학생도 되길 원했음.

그런데, 이렇게 되니까 이러한 분반 관리자 전용 API를 호출할 때마다 class_id가 필요해짐;
즉, 어느 분반에서는 조교이고 어느분반에서는 학생이기에 -> 이 호출한 사용자가 조교인지를 파악하려면 class_id가 필수적

그리고 user단에 권한이 그냥 바로 있으면 이러한 관리자 검증이 user select 한번으로 끝나는데 -> 현재는 user_belong_class에 권한이 존재하니까 추가적인 호출이 또 필요해지는 상황

이럴바에는 그냥 한 아이디로 조교와 학생이 둘 다 될 수 있다는 전제를 버리고, -> 세종 OJ처럼 TA16011092(조교 아이디) / 16011092(학생 아이디) 로 진행하는게 훨씬 효율적이고 더 간편해보인다.
왜 세종 OJ가 아이디를 분리했을까 싶기도 하네요.. 점점 더

**Comment by iml1111** [comment]
> 그리고 user단에 권한이 그냥 바로 있으면 이러한 관리자 검증이 user select 한번으로 끝나는데 -> 현재는 user_belong_class에 권한이 존재하니까 추가적인 호출이 또 필요해지는 상황

한 유저가 복수의 권한을 가질 수 있기 때문에 이렇게 설계된게 아닌가??

**Comment by 837477** [comment]
해결!
