### ISSUE TITLE
SELECT Query Validator 구현

### ISSUE THREAD

**Issue by iml1111** [iml1111/SejongSQL#6]
입력한 쿼리에 대하여 SELECT Query인지 판별하는 모듈 구현

### 대략적인 체크 방식
- Explain문구를 붙여서 해당 코드 실행 -> 정상 실행이 안될 경우 실패 (분기 반환)
- Explain 타입이 SELECT 외의 것일 경우, False 반환 (설령 다른 것일지라도 Explain에 의해 실행되면 무효화됨)
- 그 외에는 어떡하지?

### 걱정되는 점
- Explain도 결국엔 쿼리를 직접 실행한다는 점인데.. 가능하면 실행하지 않고 판별하는게 베스트긴 해서, 이 부분 경준님 도움 좀 받고 싶긴 함.

### SELECT 쿼리 외의 지원하는 다른 타입들
- DELETE
- UPDATE
- INSERT
- REPLACE
### 특이사항
- 해당 쿼리가 문법에러가 아닌 논리에러 발생시에도 익스플레인 자체는 실행되긴 함 (신기하네...)

**Comment by backgroundjun** [comment]
사용자에게 입력받은 Query를 동적 분석이 아닌, 정적 분석으로 정확하게 Validation 하기 위해서는 **구문 분석**을 하는 수 밖에 없을 듯 합니다.

MySQL Query를 추상 구문 트리로 변형하는 라이브러리를 찾아보고, 없다면 다른 방법을 찾아보아야 할 것으로 보입니다.

**Comment by backgroundjun** [comment]
또는... 최후의 방법으로 MySQL Query를 추상 구문 트리로 변형하는 라이브러리를 직접 개발하는 방법도 있겠습니다.

**Comment by iml1111** [comment]
### SELECT 쿼리 외의 지원하는 다른 타입들
- DELETE
- UPDATE
- INSERT
- REPLACE

### 특이사항
- 해당 쿼리가 문법에러가 아닌 논리에러 발생시에도 익스플레인 자체는 실행되긴 함 (신기하네...)
