### ISSUE TITLE
문제 제출 API 에러

### ISSUE THREAD

**Issue by altmshfkgudtjr** [iml1111/SejongSQL#68]
문제 제출 API에서 404 에러가 반환되었습니다.
확인부탁드립니다.

URL: `/api/v1/problems/1/submit`

<img width="253" alt="image" src="https://user-images.githubusercontent.com/47492535/169648329-3baab092-ba46-4125-b821-2360934ac437.png">

**Comment by akshxl09** [comment]
문제 제출 API는 아직 구현되지 않았습니다!
