### ISSUE TITLE
Problem Run 시 SELECT Statement 임에도 SELECT 가 아니라고 반환

### ISSUE THREAD

**Issue by backgroundjun** [iml1111/SejongSQL#93]
# 쿼리가 SELECT 로만 시작해야 하는 한계점
`(SELECT 1);` , `SELECT 1;`
위 2 개의 쿼리는 같은 동작을 하는데, ( 로 시작하는 바람에 Validator 에서 SELECT 문이 아니라는 에러가 반환됩니다.

# 프로그래머스에서 같은 코드 실행
![image](https://user-images.githubusercontent.com/93336448/170825561-268a628b-3e40-4189-94df-e4e11040f0f8.png)

**Comment by iml1111** [comment]
Advanced Quary Validator가 적용된 후, 이부분 수정하여 반영하겠습니다
